### ISSUE TITLE
Homepage for a logged in users

### ISSUE THREAD

**Issue by Vladk2** [nole23/client-angular#1]
### Description:
We have to create a homepage, on which logged user will be able to see all his profiles and choose which one he want to use (user can be an admin and can have multiple tenant or employee profiles).  Homepage should have profile info and logout buttons, as well as a 'register as a new tenant' button.

### Tasks:

- [x] Design a page.
- [x] Get required user's info from a server.
- [x] Restrict unauthorized users to access a homepage.

### Acceptance Criteria:

- [x] The user can only access this page when he's logged in.
- [x] Unauthorized user will be redirected on the login page.
- [x] The logged-in user will see, and be able to click on one of his profiles:
- Admin panel 
- Employee profile(s): (along with the name of the firm in which he works)
- Tenant profile(s): (along with the address of the building in which he lives)

**Comment by foo4foo** [comment]
Registering new abode for user finished.
