### ISSUE TITLE
Surveys

### ISSUE THREAD

**Issue by foo4foo** [nole23/client-angular#11]
### Description:
Create surveys page for tenants.

### Tasks:

- [x] Tenant is able to see active surveys for his building.
- [x] Survey creator may see report.
- [x] Tenant can fill out the survey form and answer on questions.
- [x] Supervisors and survey creators can delete surveys.
- [x] Tenants can create new surveys.

### Acceptance Criteria:

- [x] Design table for displaying a list of surveys.
- [x] Add button for survey responses.
- [x] Add button for deleting surveys (only if tenant is also building supervisor)
- [x] Add button for creating surveys.

**Comment by foo4foo** [comment]
Change URLs to English.
