### ISSUE TITLE
Create Admin module

### ISSUE THREAD

**Issue by nole23** [nole23/client-angular#15]
### Description:
Create module for admins component and add firm, building models

### Tasks:

- [x] Create admin module
- [x] Create firm models
- [x] Create building models
