### ISSUE TITLE
Employee component

### ISSUE THREAD

**Issue by nole23** [nole23/client-angular#17]
### Description:
Create EmployeeComponent and make upadate profile and add or remove employee

### Tasks:

- [x] employee-home.component - show information 
- [x] employee-list.component - show all employee on firms
- [x] employee-new.component - add new employee
