### ISSUE TITLE
Parliament Meeting

### ISSUE THREAD

**Issue by Vladk2** [nole23/client-angular#2]
### Description:
How parliament meeting should work:
- President is announcing a date of a parliament meeting.
- Before the date of the parliament, owners of apartments can propose points on the agenda.
- When the parliament starts, tenants (apartment owners) can vote for the proposed points.
- When voting is over, president must create a record from that meeting, which will be posted on the building (homepage).

### Tasks:

- [x] Create a parliament-home component
- [x] Create particular components for parliament announcemet, record creation, proposing and voting..
- [x] Allow users to access those components based on user role and parliament status (announced/started/none..)
- [x] Agenda points are accepted if there's more that 50% positive votes. At least 3 users have to vote.

### Acceptance Criteria:

- [x] President is able to:
    - Announce a date of a meeting.
    - When parliament starts and voting is done, get all accepted votes and create a meeting record
- [x] Tenant (apartment owner) is able to:
    - When parliament meeting is announced, propose agenda points.
    - When parliament starts, vote for proposed agenda points.

### Bug reports:
/
