### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by nole23** [nole23/client-angular#4]
### Description: 
I have to create a homepage for Admin panel. I have create lists for buildings, and firms and users.

### Tasks:

- [x] Desing a page
- [x] Create admin home component
- [x] Create admin list component for buildings
- [x] Create admin list component for firms
- [x] Create admin list component for users
- [x] Create admin news component for building
- [x] Create admin new component for firm

### Acceptance Criteria:

- Admin is able to:
    - [x] Update the profile information
    - [x] Change password
    - [x] Add new system admin
    - [x] Add new building
    - [x] Add new firm
    - [x] Remove system admin
    - [x] Delete fimr
    - [x] View all buildings
    - [x] View all firms
    - [x] View all users
