### ISSUE TITLE
Functionality of problems/malfunctions

### ISSUE THREAD

**Issue by Vladk2** [nole23/client-angular#6]
### Description:
Tenant is able to post a problem. Problem can be based on his apartment or on the whole building. If problem is based on the whole building, then that problem is automatically proposed as an agenda point when next parliament meeting is announced. When problem is posted, tenant and the responsible person can post comments. Automatically, the president is the responsible person, but he can forward that role to some firm (to employees of that firm, to be exact), and that firm can forward it to another firm, etc.
Responsible person can also set a repair date, and tenant, if everything went well and problem is fixed, can close that problem.

### Tasks:

- [ ] Create two components - One with all active problems, and the other for posting a problem.
- [ ] Post a problem - Problem should have title, description and (optionally) images of that problem.
- [ ] Make sure that only tenant and the responsible person can see and interact on that problem.

### Acceptance Criteria:

- Tenant who posted a problem can:
    - [ ] Post comments on a problem.
    - [ ] Close a problem.
- Responsible person for that problem can:
    - [ ] Post comments on a problem.
    - [ ] Forward that problem (so he's not a responsible person anymore)
    - [ ] Set a repair date.

### Bug reports:
/
