### ISSUE TITLE
User profile update

### ISSUE THREAD

**Issue by foo4foo** [nole23/client-angular#8]
### Description:
User can navigate to his profile page and edit his/her information.

### Tasks:

- [x] Create link on username in navigation bar
- [x] Create information input form
- [x] Update form with user data
- [x] Send new data to server and update page 
- [x] Delete account

### Acceptance Criteria:

- [x] User can't enter badly formatted email address
- [x] If user enters already taken email or username, message will be displayed
